### PR TITLE
qbittorrent: Added option to use themepark

### PR DESCRIPTION
**Pull request by ghost**
# Description

Copied the plex role themepark setup into qbittorrent role.

# How Has This Been Tested?

Tested on machine, enabled via inventory and disabled (default).

P.S First ever commit / pull req. Please let me know if I did anything wrong!

### CODE REVIEW

**Comment by enak-nalla** [comment]
Forgot to test changing back to disabling themepark after running while enabled. Causes an error due to themepark script updating the conf with `WebUI\RootFolder=/themepark`

That line would need to be deleted if themepark_enabled = false.

Don't know if I can edit a pr so closing this so it doesn't get commited.

**Comment by saltydk** [comment]
You can edit the branch and changes will show up here as long as the issue is open.

**Comment by enak-nalla** [comment]
Woops I already deleted the branch.

The fix however is to add 
```
- name: Post-Install | Settings | Remove 'WebUI\RootFolder' from 'qbittorrent.conf'
  ini_file:
    path: '{{ qbittorrent_paths_conf }}'
    section: Preferences
    option: WebUI\RootFolder
    state: absent
  when: qbittorrent_paths_conf_stat.stat.exists

- name: Post-Install | Settings | Remove 'WebUI\AlternativeUIEnabled' from 'qbittorrent.conf'
  ini_file:
    path: '{{ qbittorrent_paths_conf }}'
    section: Preferences
    option: WebUI\AlternativeUIEnabled=true
    state: absent
 when: qbittorrent_paths_conf_stat.stat.exists
```

into roles/qbittorrent/tasks/subtasks/pre-install/main.yml

Tested a fresh role (no container or /opt) with theme enabled and disabled
Tested with theme enabled, changed to disabled and running the tag again and vice versa
Running tag with no changes

If enabled the themepark script adds those lines to the config so deleting them has no impact when re running the role.
I see an issue where someone has one of those settings enabled for something outside of this themepark implementation however.

**Comment by saltydk** [comment]
You could parse the line for what theme.park sets it to and only remove it when it is true.

**Pull request closed without merging**
