### PR TITLE
mkvtoolnix: New role

### PR DESCRIPTION
**Pull request by sevospl**
# Description

MKVToolNix is a small collection of tools (mkvmerge, mkvinfo, mkvextract, mkvpropedit and mmg) that allows you to manipulate Matroska (MKV) files in several ways.

The following role `mkvtoolnix` uses a Docker image `jlesage/mkvtoolnix` which is shipped with VNC. Due to security reasons (access to files), Authelia middleware was used here.

# How Has This Been Tested?

I've run the role and everything worked as expected.

# New Role Checklist:

- [❌] <not ready yet> I have reviewed the [Contribute page in the wiki](https://docs.saltbox.dev/xxxx)
- [✔️] I have updated the header in any files I may have used as templates with my own information
- [✔️] I have added my new role to `community.yml`
- [✔️] I have verified that any Docker images used are current and supported.
- [❌] I have made corresponding changes to the documentation or have submitted a separate PR to the docs repo for this purpose.

### CODE REVIEW

**Comment by maximuskowalski** [comment]
I will try to test this later today but can see there are some minor formatting issues that will need to be addressed.

**Comment by maximuskowalski** [comment]
I have made a PR to your branch with various fixes, look through and see saltbox style formatting and how it lines up to lines above.

Also notes about branch name and "bazarr_doocker_vol_theme" 

I have installed and checked it works, but have not used it to perform any tasks.

**Comment by maximuskowalski** [comment]
I did submitted a PR to sevospl repo with that fix and others already made but as far as I know it has not been accepted.

**Comment by saltydk** [comment]
> I did submitted a PR to sevospl repo with that fix and others already made but as far as I know it has not been accepted.

Will wait for that to get merged then.

**Comment by sevospl** [comment]
@saltydk @maximuskowalski

Sorry for the delay. The PR has been merged now.

**Comment by saltydk** [comment]
Could we have this moved to the new sandbox repo? Stuff I personally don't plan to maintain will exist there.

**Comment by saltydk** [comment]
closed in favor of https://github.com/saltyorg/Sandbox/pull/3

**Pull request closed without merging**
